/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.ic5701.dfa

class App {
    fun run() {
        val code = "count,_temp,x"
        val scanner = Scanner(code)

        var token: Token
        do {
            token = scanner.next()
            println(token)
        } while (token.type != TokenType.EOF)
    }
}

fun main() {
    println(App().run())
}
