/*
 * This source file was generated by the Gradle 'init' task
 */
package edu.ic5701.dfa

class App {
    fun run() {
        val code = """
            coef1 <- 4; coef2 <- -2; coef3 <- 7;
            x <- 3;
            term1 <- coef1 * x * x;
            term2 <- coef2 * x;
            poly <- term1 + term2 + coef3;
            print poly;
        """.trimIndent()

        val scanner = Scanner(code)

        var token: Token
        do {
            token = scanner.next()
            println(token)
        } while (token.type != TokenType.EOF)
    }
}

fun main() {
    println(App().run())
}
